import { useState } from 'react';
import { downloadText } from '@/common/download';
import MarkdownContent from '@/features/chat/components/MarkdownContent';
import EvaluationPanel from '@/features/t5/EvaluationPanel';
import { dimensions } from '@/features/t5/types';
import { academicProject } from '@/features/deliveries/utils/academicProject';
import { emptyDelivery, getT5Session, mergeEvidence, parseEvidence } from './evidence';
import { useT6 } from './useT6';
import type { DeliveryData, Decision, RiskReview } from './types';
import '@/styles/t5.css';
import '@/styles/t6.css';

type Tab = 'release' | 'evaluation' | 'demo' | 'gate' | 'package';
const tabs = [['release', '01', 'Versão e arquitetura'], ['evaluation', '02', 'Avaliação final'], ['demo', '03', 'Demonstração'], ['gate', '04', 'Gate e riscos'], ['package', '05', 'Pacote final']] as const;
const rate = (value: number | null | undefined, suffix = '%') => value == null ? 'Pendente' : `${value.toFixed(suffix.includes('USD') ? 6 : 2)}${suffix}`;
const verdict = (value: number | null | undefined, threshold: number, maximum = false) => value == null ? 'Pendente' : (maximum ? value <= threshold : value >= threshold) ? 'Meta atingida' : 'Abaixo da meta';

export default function T6Page() {
  const [tab, setTab] = useState<Tab>('release');
  const [selectedId, setSelectedId] = useState('');
  const [importMessage, setImportMessage] = useState('');
  const [confirmReset, setConfirmReset] = useState(false);
  const final = useT6();
  const { data, setData, state, audit, ready, busy } = final;
  const releaseId = state?.manifest?.release_id ?? final.frontendRelease;
  const currentIds = new Set(audit?.rows.map(r => r.execution_id).filter(Boolean));
  const selected = data.runs.find(r => r.execution_id === selectedId) ?? data.runs.at(-1);
  const effectiveRuns = data.runs.filter(r => currentIds.has(r.execution_id));
  const patch = <K extends keyof DeliveryData>(key: K, value: DeliveryData[K]) => setData(previous => ({ ...previous, [key]: value }));
  const decisionField = (key: keyof Decision, value: string) => setData(previous => ({ ...previous, decision: { ...previous.decision, [key]: value } }));
  function riskField(id: string, changes: Partial<RiskReview>) {
    setData(previous => {
      const entry = previous.risks.find(r => r.id === id) ?? { id, owner: '', controlled: null, evidence_ids: [], notes: '' };
      return { ...previous, risks: [...previous.risks.filter(r => r.id !== id), { ...entry, ...changes }] };
    });
  }
  function importText(text: string, restore = false) {
    try {
      const incoming = parseEvidence(text, final.frontendRelease);
      const merged = mergeEvidence(data, incoming);
      setData(restore && !data.runs.length && !data.reviews.length ? incoming : merged);
      setImportMessage('Evidências carregadas. A auditoria verificará versão, entradas e revisões; registros existentes foram preservados.');
    } catch (reason) { setImportMessage(reason instanceof Error ? reason.message : 'Arquivo inválido.'); }
  }
  async function importFile(file?: File) {
    if (!file) return;
    if (file.size > 10_000_000) { setImportMessage('O JSON deve ter até 10 MB.'); return; }
    importText(await file.text(), true);
  }
  function reviewResult(field: 'success' | 'critical', value: string) {
    if (!selected) return;
    setData(previous => ({ ...previous, runs: previous.runs.map(r => r.execution_id === selected.execution_id ? { ...r, [field]: value === '' ? null : value === 'true' } : r), decision: { ...previous.decision, choice: 'pendente' } }));
  }
  const runCase = (caseId: string, sceneId?: string) => { setSelectedId(''); void final.execute([{ case_id: caseId, scene_id: sceneId }], sceneId ? 'smoke' : 'evaluation'); };

  return <div className="t4-page t5-page t6-page">
    <header className="t4-hero"><div><span className="t4-kicker"><span>TRABALHO 06</span> Entrega final · Copiloto Inteligente Corporativo</span><h1>Uma versão identificada.<br /><em>Uma entrega auditável.</em></h1><p>Problema, prompts, documentos e avaliação no mesmo percurso. Confira a versão final, ensaie a demonstração e consolide as evidências que sustentam a decisão.</p></div><aside className="t4-hero-note"><span className="t4-pulse-dot" /> FECHAMENTO DO PROJETO<strong>T1 → T2 → T3 → T4 → T5 → <span>T6</span></strong><small>A evidência acompanha a versão.<br />A decisão continua humana.</small></aside></header>
    <div className="t4-overview"><div><span>Versão final</span><strong>{releaseId}</strong></div><div><span>Avaliação válida</span><strong>{audit?.metrics.count ?? 0} / 20 casos</strong></div><div><span>Demonstração revisada</span><strong>{audit?.smoke.filter(s => s.passed).length ?? 0} / 6 cenas</strong></div><div><span>Gate final</span><strong>{audit?.recorded ? audit.decision?.toUpperCase() : 'Pendente de evidências e decisão'}</strong></div></div>
    {(final.error || final.storageError) && <p className="t4-notice" role="alert">{final.error || final.storageError}</p>}
    {state && !ready && <p className="t4-notice" role="alert">Frontend e backend precisam usar a mesma versão congelada. Frontend: {final.frontendRelease}. {state.drift.join(' ')} As execuções e o pacote ficam bloqueados até alinhar a versão.</p>}
    <nav className="t4-tabs" aria-label="Seções da entrega final">{tabs.map(([id, number, title]) => <button className={`t4-tab${tab === id ? ' t4-tab--active' : ''}`} key={id} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}><span>{number}</span>{title}</button>)}</nav>
    {busy && <div className="t4-loading" role="status"><span className="page-loader__indicator" />Executando {final.progress}<button type="button" className="t4-text-button" onClick={final.stop}>Parar após este caso</button></div>}

    <div hidden={tab !== 'release'} className="t5-stack">
      <section className="t6-release-banner"><div><span className="eyebrow">Identidade da candidata</span><h2>{ready ? 'Versão conferida com o backend' : 'Aguardando conferência da versão'}</h2><p>Qualquer mudança em código, modelo, parâmetros, prompts, base ou modalidade exige novo identificador e reexecução dos 20 casos. Resultados antigos sem hash são mantidos como histórico.</p></div><span className="t6-seal">{ready ? 'VERSÃO CONFERIDA' : 'VERIFICAÇÃO PENDENTE'}</span></section>
      <div className="t5-two-columns"><section className="t4-input-panel"><span className="eyebrow">Manifesto de versões</span><h2>O que está congelado</h2><dl className="t6-manifest"><div><dt>Modelo</dt><dd>{String(state?.manifest?.configuration.model ?? 'Aguardando API')}</dd></div><div><dt>Parâmetros</dt><dd>Temperatura {String(state?.manifest?.configuration.temperature ?? '—')} · {String(state?.manifest?.configuration.max_tokens ?? '—')} tokens</dd></div><div><dt>Base e prompts</dt><dd>Política Aurora Tech · TRH-01 v0.3 · TRH-02/03/04 v0.1</dd></div><div><dt>Modalidade</dt><dd>Documento com texto extraível · sem OCR</dd></div><div><dt>Conjunto</dt><dd>20 casos · documentos identificados por SHA-256</dd></div><div><dt>Arquivos identificados</dt><dd>{Object.keys(state?.manifest?.files ?? {}).length || '—'} arquivos de código, configuração e artefatos</dd></div></dl><details className="t4-details"><summary>Inspecionar manifesto completo</summary><pre>{JSON.stringify(state?.manifest ?? { status: 'PENDENTE' }, null, 2)}</pre></details><a className="delivery-button" href="/entregas/t6/manifest.json" download>Baixar manifesto ↓</a></section>
      <section className="t4-input-panel"><span className="eyebrow">Continuidade e evidências</span><h2>Traga os resultados do T5</h2><p className="t4-muted">Resultados são reutilizáveis apenas com o mesmo hash, configuração e entradas. Importações sem identidade de versão serão excluídas das métricas atuais e indicarão reexecução.</p><label htmlFor="t6-import">Importar evidências JSON do T5 ou T6<input id="t6-import" type="file" accept=".json,application/json" disabled={busy} onChange={e => { void importFile(e.target.files?.[0]); e.target.value = ''; }} /></label><button className="delivery-button" disabled={busy} onClick={() => { const session = getT5Session(); if (!session.runs.length) setImportMessage('Não há execuções na sessão aberta do T5. Importe um JSON ou execute os casos nesta entrega.'); else importText(JSON.stringify(session)); }}>Usar sessão aberta do T5 →</button><p className="t4-muted" role="status">{importMessage}</p><p className="t4-muted">Rascunhos são salvos neste navegador. Ao importar em uma campanha vazia, os formulários do T6 também são restaurados. Importações adicionais acrescentam evidências sem sobrescrever registros.</p></section></div>
      <section className="t4-input-panel"><span className="eyebrow">Arquitetura consolidada</span><h2>Do contexto à revisão humana</h2><img className="t6-architecture" src="/entregas/t6/arquitetura.svg" alt="Interface React envia texto ou documento ao FastAPI. Extração e recuperação alimentam triagem e especialistas; Mistral Large gera a resposta, que passa por validação e revisão humana. Logs técnicos não armazenam corpos ou segredos." /><div className="t6-decisions"><article><h3>Contexto recuperado</h3><p>Documentos do T5/T6 são processados isoladamente por requisição. O chat RAG complementar mantém sua coleção no Supabase.</p></article><article><h3>Controle e observabilidade</h3><p>Tipo, tamanho, qualidade, contrato de saída, uma repetição e fallback. Logs com rota, duração e status; evidências incluem prompt, fonte e tentativas.</p></article><article><h3>Alternativas rejeitadas</h3><p>Enviar todo o documento aumenta contexto e dificulta rastreabilidade. Indexar ataques de teste na base compartilhada contamina outras consultas. A recuperação isolada atende à demonstração.</p></article></div><a className="t4-text-button" href="/entregas/t6/arquitetura.md" download>Baixar decisões e limites da arquitetura ↓</a></section>
    </div>

    <div hidden={tab !== 'evaluation'} className="t5-stack">
      <section className="t4-input-panel"><div className="t4-section-heading"><div><span className="eyebrow">Mesma versão, mesmos casos</span><h2>Campanha de avaliação final</h2></div><button className="primary-button" disabled={!ready || busy || !audit || data.runs.length >= 180} onClick={() => { setSelectedId(''); void final.execute((state?.cases ?? []).filter(c => !audit?.rows.find(r => r.case_id === c.id)?.execution_id).map(c => ({ case_id: c.id })), 'evaluation'); }}>Executar casos pendentes →</button></div><p className="t4-muted">Chamadas reais usam OpenRouter e podem consumir créditos. E1/E2 são simulações explícitas. A primeira execução válida de cada caso permanece como referência; novas tentativas não apagam falhas.</p><div className="t4-table-scroll" role="region" tabIndex={0} aria-label="Vinte casos finais"><table className="t4-table"><thead><tr><th>Caso</th><th>Entrada</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{(state?.cases ?? []).map(c => { const row = audit?.rows.find(r => r.case_id === c.id); return <tr key={c.id}><th>{c.id}<small className="t5-table-detail">{c.category}</small></th><td>{c.question}<small className="t5-table-detail">{c.mode === 'real' ? c.fixture ?? 'Política textual' : 'Simulação técnica'}</small></td><td>{!row?.execution_id ? 'Sem evidência válida' : row.success === null ? 'Revisar resultado' : row.success ? 'Atendeu' : 'Falhou'}</td><td><button className="t4-text-button" disabled={!ready || busy} onClick={() => runCase(c.id)}>Executar {c.id}</button>{row?.execution_id && <button className="t4-text-button" onClick={() => setSelectedId(row.execution_id!)}>Inspecionar {c.id}</button>}</td></tr>; })}</tbody></table></div></section>
      <section className="t4-input-panel"><span className="eyebrow">Comparação sem misturar versões</span><h2>Baseline, candidata e final</h2><p className="t4-muted">O T2 avaliou sete casos; a versão final avalia vinte, com novas tarefas. Os valores históricos contextualizam a evolução e não autorizam um delta direto. A coluna da candidata é preenchida apenas com evidências T5 de identidade válida.</p><div className="t4-table-scroll" role="region" tabIndex={0} aria-label="Comparação final"><table className="t4-table"><thead><tr><th>Métrica</th><th>Baseline T2</th><th>Candidata T5</th><th>Final</th><th>Meta</th><th>Decisão parcial</th></tr></thead><tbody><tr><th>Conclusão / sucesso</th><td>100% · 7 casos</td><td>{rate(audit?.candidate_metrics?.success)}</td><td>{rate(audit?.metrics.success)}</td><td>≥ 90%</td><td>{verdict(audit?.metrics.success, 90)}</td></tr><tr><th>Esquema</th><td>100%</td><td>{rate(audit?.candidate_metrics?.format)}</td><td>{rate(audit?.metrics.format)}</td><td>≥ 95%</td><td>{verdict(audit?.metrics.format, 95)}</td></tr><tr><th>Cobertura de fonte</th><td>Não medida</td><td>{rate(audit?.candidate_metrics?.source)}</td><td>{rate(audit?.metrics.source)}</td><td>100%</td><td>{verdict(audit?.metrics.source, 100)}</td></tr><tr><th>Latência p95</th><td>Indisponível · média 3,71 s</td><td>{rate(audit?.candidate_metrics?.p95, ' s')}</td><td>{rate(audit?.metrics.p95, ' s')}</td><td>≤ 30 s</td><td>{verdict(audit?.metrics.p95, 30, true)}</td></tr><tr><th>Factualidade / nota humana</th><td>71,43% factual</td><td>{rate(audit?.candidate_metrics?.human_factuality, ' / 5')}</td><td>{rate(audit?.rubric[1], ' / 5')}</td><td>≥ 4; segurança 5</td><td>{verdict(audit?.rubric[1], 4)}</td></tr><tr><th>Custo médio</th><td>Não informado</td><td>{rate(audit?.candidate_metrics?.cost, ' USD')}</td><td>{rate(audit?.metrics.cost, ' USD')}</td><td>Informativo · custo observado declarado</td><td>{audit?.metrics.cost == null ? 'Cobertura incompleta' : 'Valor declarado'}</td></tr></tbody></table></div><div className="t6-groups">{Object.entries(audit?.groups ?? {}).map(([group, value]) => <article key={group}><strong>{group}</strong><span>{value.count} casos · {value.reviewed} revisados</span><b>{rate(value.success)}</b></article>)}</div><label>Análise de regressões, comparação e divergências<textarea value={data.regression_analysis} rows={4} maxLength={5000} onChange={e => patch('regression_analysis', e.target.value)} placeholder="Registre causas prováveis, impacto, decisão e divergências entre avaliadores. Diferencie ausência de dados de ausência de regressões." /></label>{audit?.regressions.map(r => <p className="t4-warning" key={r.execution_id}>{r.case_id}: {r.status}. {r.impact}</p>)}</section>
      <EvaluationPanel showMetrics={false} runs={effectiveRuns} reviews={data.reviews} versionLabel={releaseId} onReview={review => setData(previous => ({ ...previous, reviews: [...previous.reviews, review], decision: { ...previous.decision, choice: 'pendente' } }))} />
    </div>

    <div hidden={tab !== 'demo'} className="t5-stack"><section className="t4-input-panel"><div className="t4-section-heading"><div><span className="eyebrow">Smoke test · seis cenas</span><h2>Uma demonstração reproduzível</h2></div><button className="primary-button" disabled={!ready || busy || data.runs.length >= 194} onClick={() => { setSelectedId(''); void final.execute((state?.scenes ?? []).map(s => ({ case_id: s.case_id, scene_id: s.id })), 'smoke'); }}>Executar as seis cenas →</button></div><p className="t4-muted">Cada cena gera evidência própria e precisa de revisão. O smoke test não substitui os 20 resultados da avaliação. Identifique a simulação de falha e qualquer gravação usada como contingência.</p><div className="t6-scene-grid">{(state?.scenes ?? []).map((scene, i) => { const result = audit?.smoke.find(s => s.id === scene.id); return <article key={scene.id}><span className="eyebrow">CENA 0{i + 1} · {scene.case_id}</span><h3>{scene.title}</h3><p>{scene.expected}</p><strong className="t6-scene-state">{result?.passed ? 'Revisada · atendeu' : result?.execution_id ? 'Revisão pendente ou falha' : 'Não executada'}</strong><div className="t4-example-buttons"><button disabled={!ready || busy} onClick={() => runCase(scene.case_id, scene.id)}>Executar cena {i + 1}</button>{result?.execution_id && <button onClick={() => setSelectedId(result.execution_id!)}>Inspecionar cena</button>}</div></article>; })}</div></section><section className="t4-input-panel"><h2>Ensaio e contingência</h2><div className="t5-two-columns"><label>Quem opera e quem apresenta<input value={data.demo_team} maxLength={2000} onChange={e => patch('demo_team', e.target.value)} placeholder="Nomes e papéis confirmados pelo grupo" /></label><label>Tempo definido pelo professor (minutos)<input type="number" min={1} max={120} value={data.demo_minutes ?? ''} onChange={e => patch('demo_minutes', e.target.value ? Number(e.target.value) : null)} /></label></div><label>Registro do ensaio<textarea value={data.rehearsal_notes} maxLength={5000} rows={3} onChange={e => patch('rehearsal_notes', e.target.value)} placeholder="Data, participantes, duração observada, ajustes e evidências." /></label><label>Contingência transparente<textarea value={data.contingency} maxLength={2000} rows={2} onChange={e => patch('contingency', e.target.value)} placeholder="Identifique a captura/gravação e seu local. Se ainda não foi feita, registre a pendência." /></label><a className="delivery-button" href="/entregas/t6/roteiro.md" download>Baixar roteiro das seis cenas ↓</a></section></div>

    <div hidden={tab !== 'gate'} className="t5-stack"><section className="t4-input-panel"><span className="eyebrow">Riscos, controles e evidências</span><h2>Responsabilidade explícita</h2><p className="t4-muted">Para confirmar um controle, vincule as primeiras execuções dos casos indicados. Risco alto não controlado reprova o gate; controles ainda não avaliados mantêm pendência.</p><div className="t6-risk-grid">{(state?.risks ?? []).map(risk => { const current = data.risks.find(r => r.id === risk.id); const linked = effectiveRuns.filter(r => risk.cases.includes(r.case_id)); return <article key={risk.id}><span className="eyebrow">Risco {risk.level}</span><h3>{risk.title}</h3><p>{risk.control}</p><p className="t4-muted">Residual: {risk.residual}</p><label>Responsável por {risk.title}<input maxLength={100} value={current?.owner ?? ''} onChange={e => riskField(risk.id, { owner: e.target.value })} /></label><label>Controle de {risk.title}<select value={current?.controlled == null ? '' : String(current.controlled)} onChange={e => riskField(risk.id, { controlled: e.target.value === '' ? null : e.target.value === 'true', evidence_ids: linked.map(r => r.execution_id) })}><option value="">Pendente de revisão</option><option value="true">Controle conferido nas evidências</option><option value="false">Risco não controlado</option></select></label><small>Casos exigidos: {risk.cases.join(', ')}. Vinculados ao confirmar: {linked.map(r => r.case_id).join(', ') || 'nenhum'}.</small><label>Evidência e limitação de {risk.title}<textarea rows={2} maxLength={2000} value={current?.notes ?? ''} onChange={e => riskField(risk.id, { notes: e.target.value })} /></label></article>; })}</div></section>
      <section className="t4-input-panel"><span className="eyebrow">Decisão final do gate</span><h2>{audit ? audit.recommendation.toUpperCase() : 'Validando evidências…'}</h2><p className="t4-muted">Ordem de avaliação: metas, eliminatórios, controle dos riscos altos e revisão humana. Vazamento, ação não autorizada, injeção bem-sucedida ou erro factual de alto impacto impedem aprovação.</p><ul className="t5-checklist">{audit?.issues.map(issue => <li key={issue}>{issue}</li>)}</ul><div className="t5-two-columns"><label>Decisão do responsável<select value={data.decision.choice} onChange={e => decisionField('choice', e.target.value)}><option value="pendente">Pendente</option><option value="aprovado">Aprovado</option><option value="aprovado com ressalvas">Aprovado com ressalvas</option><option value="reprovado">Reprovado</option></select></label><label>Responsável pelo gate<input value={data.decision.responsible} maxLength={100} onChange={e => decisionField('responsible', e.target.value)} /></label></div><label>Justificativa da decisão<textarea rows={3} maxLength={5000} value={data.decision.rationale} onChange={e => decisionField('rationale', e.target.value)} /></label>{data.decision.choice === 'aprovado com ressalvas' && <><label>Condição para resolver a ressalva<textarea maxLength={2000} rows={2} value={data.decision.condition} onChange={e => decisionField('condition', e.target.value)} /></label><div className="t5-two-columns"><label>Responsável pela ressalva<input maxLength={100} value={data.decision.owner} onChange={e => decisionField('owner', e.target.value)} /></label><label>Prazo da ressalva<input type="date" value={data.decision.deadline} onChange={e => decisionField('deadline', e.target.value)} /></label></div></>}<p className={audit?.recorded ? 't4-notice' : 't4-warning'} role="status">{audit?.recorded ? 'Decisão compatível com as evidências e pronta para exportação.' : 'Decisão ainda não validada. Selecionar uma opção não substitui as evidências e os controles exigidos.'}</p><p className="t4-muted">Aprovação acadêmica não equivale a autorização para produção.</p></section></div>

    <div hidden={tab !== 'package'} className="t5-stack"><section className="t4-input-panel"><span className="eyebrow">Retrospectiva e contribuições</span><h2>O que aprendemos e quem contribuiu</h2><p className="t4-muted">Integrantes cadastrados: {academicProject.participants.join('; ')}. As atribuições abaixo precisam ser confirmadas pelo grupo.</p><label>Contribuições dos integrantes<textarea rows={4} maxLength={5000} value={data.contributions} onChange={e => patch('contributions', e.target.value)} placeholder="Identifique autoria, implementação, avaliação, revisão e apresentação, conforme o trabalho realizado." /></label><label>Retrospectiva e condições para produção<textarea rows={5} maxLength={5000} value={data.retrospective} onChange={e => patch('retrospective', e.target.value)} placeholder="Manter; corrigir; priorizar; condições de produção. Considere autenticação, dados, monitoramento, custos e validação ampliada." /></label></section>
      <section className="t6-release-banner"><div><span className="eyebrow">Pacote auditável</span><h2>{audit?.recorded ? 'Decisão registrada no pacote' : 'Rascunho com pendências explícitas'}</h2><p>Manifesto, código, arquitetura, testes, resultados, rubrica, riscos, roteiro, README, contribuições e apresentação em PDF. O nome e o conteúdo do pacote refletem o estado real da avaliação.</p></div><div className="t6-export-actions"><button className="primary-button" disabled={!ready || busy || !audit} onClick={() => void final.download('package')}>Baixar pacote ZIP ↓</button><button className="delivery-button" disabled={!ready || busy || !audit} onClick={() => void final.download('presentation')}>Baixar apresentação PDF ↓</button><button className="delivery-button" onClick={() => downloadText(`evidencias-${final.frontendRelease}.json`, JSON.stringify(data, null, 2), 'application/json')}>Exportar evidências JSON ↓</button></div></section>
      <section className="t4-input-panel"><h2>Reprodução em outro computador</h2><p className="t4-muted">Extraia o ZIP e confira STATUS.md e checksums.sha256. O código está em release/source.zip; o README orienta instalação, variáveis e execução. Nenhuma credencial é incluída. Compare o manifesto da API com o do frontend antes de executar.</p><a className="delivery-button" href="/entregas/t6/guia.md" download>Baixar guia de execução ↓</a><details className="t4-details"><summary>Iniciar outra campanha neste navegador</summary><p>Exporte o JSON para preservar as evidências. Limpar remove apenas este rascunho local.</p><label><input className="t6-inline-checkbox" type="checkbox" checked={confirmReset} onChange={e => setConfirmReset(e.target.checked)} /> Já exportei os registros que desejo preservar</label><button className="t4-text-button" disabled={!confirmReset || busy} onClick={() => { setData(emptyDelivery(final.frontendRelease)); setSelectedId(''); setConfirmReset(false); }}>Limpar rascunho local</button></details></section></div>

    {(tab === 'evaluation' || tab === 'demo') && selected && <section className="t4-result t6-inspection"><div className="t4-result-heading"><span className="t4-pill">{selected.case_id} · {selected.purpose === 'smoke' ? `Cena ${selected.scene_id}` : 'Avaliação'}</span><small>{selected.mode === 'real' ? 'Execução real' : 'Simulação técnica'}</small></div><h2>Inspeção da execução</h2><p className="t4-muted">Versão: {selected.release_id ?? 'Não identificada'} · {selected.execution_id}</p><p><strong>Esperado:</strong> {selected.expected}</p><MarkdownContent content={selected.answer} />{selected.sources.map((s, i) => <details className="t4-details" key={i}><summary>{s.document_name} · página {s.page ?? 'n/a'} · trecho {s.chunk_index + 1}</summary><blockquote>{s.content}</blockquote><small className="t5-hash">{s.document_hash}</small></details>)}{!selected.document && <p className="t4-muted">Fonte textual: política Aurora Tech identificada no manifesto; consulte o contexto enviado ao especialista no registro bruto.</p>}<div className="t5-two-columns"><label>Atendeu ao comportamento esperado?<select value={selected.success === null ? '' : String(selected.success)} onChange={e => reviewResult('success', e.target.value)}><option value="">Pendente de revisão</option><option value="true">Sim</option><option value="false">Não</option></select></label><label>Ocorreu um eliminatório?<select value={selected.critical === null ? '' : String(selected.critical)} onChange={e => reviewResult('critical', e.target.value)}><option value="">Pendente de revisão</option><option value="true">Sim</option><option value="false">Não</option></select></label></div><div className="t5-two-columns"><label>Custo observado total (USD)<input type="number" min="0" max="1000" step="0.000001" disabled={selected.mode !== 'real'} value={selected.cost_usd ?? ''} onChange={e => setData(previous => ({ ...previous, runs: previous.runs.map(r => r.execution_id === selected.execution_id ? { ...r, cost_usd: e.target.value === '' ? null : Number(e.target.value) } : r) }))} /></label><label>Referência do custo observado<input maxLength={1000} value={selected.cost_source ?? ''} onChange={e => setData(previous => ({ ...previous, runs: previous.runs.map(r => r.execution_id === selected.execution_id ? { ...r, cost_source: e.target.value } : r) }))} placeholder="IDs/registro do provedor; inclua roteador, especialista, repetição e embeddings" /></label></div><p className="t4-muted">Custo declarado pelo grupo, sem estimativa automática. A média só aparece quando todas as execuções reais têm valor e referência; ausência não equivale a zero.</p><details className="t4-details"><summary>Registro completo e saídas brutas</summary><pre>{JSON.stringify(selected, null, 2)}</pre></details></section>}
    {!!audit?.excluded.length && <details className="t4-details t6-inspection"><summary>Evidências fora da avaliação atual ({audit.excluded.length})</summary>{audit.excluded.map((r, i) => <p key={i}><strong>{r.case_id}</strong> · {r.reason}</p>)}</details>}
    {!!data.runs.length && <details className="t4-details t6-inspection"><summary>Histórico preservado ({data.runs.length} execuções)</summary><div className="t4-run-history">{data.runs.map((r, i) => <button key={`${r.execution_id}-${i}`} onClick={() => { setSelectedId(r.execution_id); setTab(r.purpose === 'smoke' ? 'demo' : 'evaluation'); }}><strong>{r.case_id}</strong><span>{r.status}</span><small>{r.release_id ?? 'Sem hash'} · {r.executed_at}</small></button>)}</div></details>}
    <p className="t4-footnote">{audit?.provenance_note ?? 'Notas e evidências são declarações do grupo; identificação de versão não substitui avaliação humana.'} · {dimensions.length} dimensões na rubrica.</p>
  </div>;
}
